### ISSUE TITLE
Navigation not working anymore

### ISSUE THREAD

**Issue by woozy** [php-integrator/atom-navigation#35] opened 2016-12-20 23:10 UTC
Hi, 

Sorry, I don't have very much to say. I just noticed that in the last weeks navigation stopped working. I have the last plugin version and also the most recent atom version and I don't notice anything weird on the developers console. 

Any advise on possible workaround / solution that I can apply?

Thank you!

**Comment by Talv** [comment] 2016-12-21 03:02
I've noticed the same after upgrade of this package & Hyperclick.

However it turns out that it does work. But binding have been changed (took me awhile to figure). They seem to be platform dependent now.
In my case, on Linux it was ALT previously, now it's CTRL.

**Comment by Gert-dev** [comment] 2016-12-21 09:16
Yes, the shortcut has indeed changed, this is also listed in [the CHANGELOG](https://github.com/php-integrator/atom-navigation/blob/master/CHANGELOG.md).

Now that the actual click handling is handled by hyperclick, it handles the defaults entirely (but they are still customizable).

**Comment by woozy** [comment] 2016-12-21 10:30
Hi, 
I'm using Mac, on Hyperclick settings I have the action defined cmd+click. It underlines methods and classes, etc. but it doesn't navigate.

**Comment by Gert-dev** [comment] 2016-12-21 13:50
@woozy Are you still experiencing https://github.com/php-integrator/atom-base/issues/259 ? In that case that issue is likely why this isn't working either :-).

**Comment by woozy** [comment] 2016-12-22 00:05
@Gert-dev yes, I do. I opened this one because I wasn't sure it could be related. Sorry! :)

**Comment by Gert-dev** [comment] 2016-12-22 09:10
@woozy No problem!

**Comment by Proteo** [comment] 2017-01-30 15:26
Hi, sorry for bringing this up again. I don't have the problem in [php-integrator/atom-base#259](https://github.com/php-integrator/atom-base/issues/259) but still, I have the same problem described by @woozy (I'm also on Mac). I uninstalled and reinstalled the whole php-integrator-* set but still, no luck. Any help would be greatly appreciated, this is a *must* package for me.

**Comment by woozy** [comment] 2017-01-30 15:53
Hi, I still experience the same issue. On Mac and also on Linux!

**Comment by Gert-dev** [comment] 2017-01-30 17:47
No problem! I assume that there is nothing out of the ordinary listed in the developer tools? Does this happen in specific locations or do things such as trying to navigate to built-in functions such as `array_walk` also fail?

**Comment by Proteo** [comment] 2017-01-30 17:57
Hi @Gert-dev. In my case, both custom and built-in functions fail silently. These are the only messages in the console:
```
The PHP server has something to say: Starting socket server on port 28292...
php-integrator-base - Indexing: 800.132ms
```
I can see the underline after triggering the key (CMD in my case), but that's it. When I click on the underlined word the underline goes away. Please let me know how can I help you to diagnose the issue.

Thanks in advance.

**Comment by Proteo** [comment] 2017-01-30 18:04
FYI: I tried restarting everything from scratch. I Renamed the ~/.atom directory to something else, fired up Atom and reinstalled only the php-integrator-* packages. Nothing, the same result.

**Comment by Gert-dev** [comment] 2017-01-30 20:11
Strange, seems like indexing did commence and do something other than just exit. Could you take a look inside the `~/.atom/packages/php-integrator-base/indexes` for the database with the same name as your project and see if it has any significant size?

If you're willing and able, you could also try opening it up and going to the table `functions` to see if there's anything in there. It contains the global functions as well as class methods. Built-in PHP stuff is indexed separately, so even if parsing fails for some reason, built-ins should at least be working.

**Comment by Proteo** [comment] 2017-01-30 20:24
Hmmm... strange thing. I've tested a Drupal project with lots of custom stuff/modules. The size of the database is 6.3 Mb, which is appropiate I think. Most important, the functions table looks good, it has 4641 rows and seems to have every function I can think of. It also includes built-in functions like array_diff, BTW.

**Comment by woozy** [comment] 2017-01-31 09:50
@Gert-dev now I think we are getting somewhere! :) on that folder I only have two files` .npignore ` and `null.sqlite`. Would this be the problem?

**Comment by ameenross** [comment] 2017-01-31 11:03
Same here. I tried various projects, but I can't seem to get anything other than a 0 byte `null.sqlite`

**Comment by ameenross** [comment] 2017-01-31 11:28
Forget I said anything. I found out php-integrator-base requires project-manager. I think it would save people a lot of trouble to make it an actual requirement, not just describe it in a wiki

**Comment by woozy** [comment] 2017-01-31 13:30
@Gert-dev agree with @ameenross. I added `atom-project-manager` and now it's working. I think this wasn't a requirement when I started to use `php-integrator` because I had navigation and autocomplete but a few month ago it stopped working.

**Comment by Gert-dev** [comment] 2017-01-31 15:19
You're absolutely right, project manager wasn't required before. It has been required since [1.2.0](https://github.com/php-integrator/atom-base/blob/master/CHANGELOG.md#120) and is mentioned in the changelog.

Out of curiosity: what could have made this change more visible for you? Would it have helped if I showed a one-time notification popup in Atom notifying you about the change after updating? I'm asking as I notice that not everyone reads changelogs and these things may not always be clear after updating. In the case of someone upgrading from 1.1, everything will just seem to break.

**Comment by woozy** [comment] 2017-01-31 15:29
@Gert-dev I think the one time notification popup would help. I usually read change logs when I suspect that the update may fix something I'm experiencing. Since php-integrator-* had been working fine I just give the order to update all the packages and don't pay much attention to it. 

Another thing could be useful is put it on readme directly. Since I was experiencing this error I doubled checked if I had everything that is on the readme (and I did) but I didn't look into the wiki.

Thanks!

**Comment by ameenross** [comment] 2017-01-31 16:34
@Gert-dev, personally I am new to this package. I tried a few other packages which promise to do the same thing. As a result, I didn't click through to the wiki. I assumed the package settings would tell me all I needed to know.

Also, I've seen other packages that tell apm that they require other stuff (which subsequently is installed automatically). I would expect that to happen here as well.

One more thing, I've now got it to work, but I have one Laravel project where indexing consistently stops at 44%. There's no error in the console, besides a notice that it's done indexing. It also results in a filled .db file. However, hyperclicking doen't work. I noticed lots of stuff from the vendor folder is in the `files` table, but hardly anything, if anything at all, from my own code. Is there any way to see debug output of the indexer?

**Comment by Gert-dev** [comment] 2017-01-31 19:31
@woozy @ameenross Thanks, that's good to know, I'll keep that in mind if I do more of these kinds of changes in the future.

@ameenross All standard output from the PHP process is printed to the developer tools, judging from your comment it seems like indexing is hanging up somewhere. You could try opening up `~/.atom/packages/php-integrator-base/core/x.x.x/src/Indexing/ProjectIndexer.php` and try dropping something like this around the function (i.e. at the start of the foreach and possible in the catch clauses) to see where it stops or is hanging: `echo $filePath . PHP_EOL;`. After that, restart Atom to restart the PHP server process and these changes should take effect (i.e. output should show up in the developer tools).

**Comment by Proteo** [comment] 2017-02-01 14:16
OK, after reading the latest developments of the issue I checked again and I realized that it's indeed working, but I have the very same issue as @ameenross: there are lots and lots of functions saved in the database file, but most of muy own custom functions aren't there; most important, even those that are in the database, are not working reliably. Even built-in PHP functions won't work most of the time.

On the good side, I noticed that functions that are added *after* the initial indexing process are properly recognized and work just fine.

**Comment by Gert-dev** [comment] 2017-02-01 20:15
I've released a new version of the core and base package that fixes an issue with heredocs with interpolated values not parsing correctly [1]. If you had a file with these anywhere, that file would fail to parse. If not, the new release is also more verbose about such parsing errors, so if there is another corner case I missed, the core should become a lot more talkative about it (rather than silencing it, like before).

[1] https://github.com/php-integrator/core/issues/82

**Comment by Proteo** [comment] 2017-02-01 22:08
Hi @Gert-dev, thanks a lot for your support and patience. I have realized that the package works wonderfully with other (non Drupal) projects, so I was intrigued to find out why. I tried adding the lines you suggested above to the `ProjectIndexer.php` file, then reindexed the project. To my surprise it reached the last file in the root directory (in alphabetical order) but the process skipped lots of files (that's why many of my functions were being ignored).

After realizing that, I finally understood the problem: the issue is that Drupal (and other projects) uses custom file extensions like .inc, .module, .install, test. a lot; I added some code to the `ProjectIndexer.php` file to test the value of the `$extensionsToIndex` parameter in the `index()` method and the array contains a single value, "php". So, mystery solved. 

Now, I'm quite sure that at some point the indexer processed these other files too, and I just checked the preferences of the PHP core package, and in PHP grammar settings it says:

`File Types: aw, ctp, inc, install, module, php, php_cs, php3, php4, php5, phpt, phtml, profile, module, install, inc, test, theme`

How can I enforce back the use of all these extensions in the indexer? Is that the solution?

**Comment by Proteo** [comment] 2017-02-01 22:36
I just noticed, there's an entry called "fileExtensions" in the `projects.cson` file for each project that has been set up to use PHP integrator. It is of course the best place to store this information, since then you can apply per-project settings, so the indexer should be fed this instead of the PHP package settings.

**Comment by Gert-dev** [comment] 2017-02-02 17:51
@Proteo No problem! I've followed your suggestion and added [a wiki page to the base package wiki](https://github.com/php-integrator/atom-base/wiki/Project-Settings) that contains some more information about the currently available project settings.

Seeing as the issue from woozy is solved and ameenross' issue is taken up in https://github.com/php-integrator/core/issues/82, I'll close this.

**Closed by Gert-dev** 2017-02-02 17:51 UTC
